# Generated by Django 5.2.16 on 2026-07-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('VAN', 'Van'), ('TRUCK', 'Truck'), ('MINI', 'Mini')], max_length=20)),
                ('maximum_load_capacity', models.DecimalField(decimal_places=2, help_text='Capacity in KG', max_digits=8)),
                ('odometer', models.PositiveIntegerField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('IN_SHOP', 'In Shop'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
    ]
