# Generated by Django 5.2.16 on 2026-07-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
