# Generated by Django 5.2.16 on 2026-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicledocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='name',
            new_name='name_model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='maximum_load_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_load_capacity_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='Van', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
