# Generated by Django 5.2.16 on 2026-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('distance_unit', models.CharField(default='km', max_length=10)),
                ('autoNotify', models.BooleanField(default=True)),
                ('strictDispatch', models.BooleanField(default=True)),
                ('restrictHours', models.BooleanField(default=False)),
                ('debugMode', models.BooleanField(default=False)),
            ],
        ),
    ]
