# Generated by Django 5.2.16 on 2026-07-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
