# Generated by Django 5.2.16 on 2026-07-12 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('FUEL', 'Fuel'), ('TOLL', 'Toll'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], max_length=20)),
                ('liters', models.DecimalField(blank=True, decimal_places=2, help_text='Only for fuel', max_digits=8, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
    ]
